# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gq82QQWWVowfEv1h5g9YI1trm2vDyTrR
"""

def analiz(genre):
    genre = genre.lower()

    if genre == "action":
        return (
            "2024/2025 Action o'yinlari:",
            """
            1) Grand Theft Auto V
            2) Assassin's Creed Valhalla
            3) Red Dead Redemption 2
            """
        )
    elif genre == "adventure":
        return (
            "2024/2025 Adventure o'yinlari:",
            """
            1) The Legend of Zelda: Tears of the Kingdom
            2) Uncharted 4: A Thief's End
            3) Tomb Raider
            """
        )
    elif genre == "rpg":
        return (
            "2024/2025 RPG o'yinlari:",
            """
            1) The Witcher 3: Wild Hunt
            2) Final Fantasy VII Remake
            3) Elden Ring
            """
        )
    elif genre == "shooter":
        return (
            "2024/2025 Shooter o'yinlari:",
            """
            1) Call of Duty: Modern Warfare II
            2) Apex Legends
            3) Battlefield 2042
            """
        )
    elif genre == "fighting":
        return (
            "2024/2025 Fighting o'yinlari:",
            """
            1) Mortal Kombat 11
            2) Tekken 7
            3) Street Fighter V
            """
        )
    elif genre == "sports":
        return (
            "2024/2025 Sports o'yinlari:",
            """
            1) FIFA 24
            2) NBA 2K24
            3) Madden NFL 24
            """
        )
    elif genre == "simulation":
        return (
            "2024/2025 Simulation o'yinlari:",
            """
            1) The Sims 4
            2) Microsoft Flight Simulator
            3) SimCity
            """
        )
    elif genre == "strategy":
        return (
            "2024/2025 Strategy o'yinlari:",
            """
            1) Civilization VI
            2) Age of Empires IV
            3) Total War: Warhammer III
            """
        )
    elif genre == "horror":
        return (
            "2024/2025 Horror o'yinlari:",
            """
            1) Resident Evil Village
            2) The Callisto Protocol
            3) Silent Hill 2 (Remake)
            """
        )
    elif genre == "puzzle":
        return (
            "2024/2025 Puzzle o'yinlari:",
            """
            1) The Witness
            2) Portal 2
            3) Tetris Effect
            """
        )
    else:
        return "Ushbu janr uchun ma'lumot yo'q", "Ma'lumot mavjud emas"

genre = input("Qaysi janr haqida bilmoqchisiz? (masalan: shooter, action, fighting,horror, puzzle, strategy,rpg,adventure) Ayting: ")
result, games = analiz(genre)
print(result)
print(games)

